on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/test.yml
    with:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ECR_REPO_NAME: ${{secrets.AWS_ECR_REPO_NAME}}
      AWS_USER_NAME: ${{ secrets.AWS_USER_NAME}}