name: Imai test

on:
  push:
    branches:
      - master
jobs:
  buiild:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@master
      - name: run script
        run: python3 test.py