name: Imai test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Login to Amazon ECR
        id: github-actions-test-user
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: user/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{steps.github-actions-test-user.outputs.registry}}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO_NAME}}
        run: |
          echo ${{steps.github-actions-test-user.outputs.registry}}
          echo ${{ github.ref }}
          docker build -t test .
          docker tag test:latest 048565253484.dkr.ecr.us-west-2.amazonaws.com/test:latest
          docker push 048565253484.dkr.ecr.us-west-2.amazonaws.com/test:latest