name: Imai test

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
     - name: Location
       run: ls & pwd
     - name: checkout
       uses: actions/checkout@master

  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
     - name: Location
       run: ls & pwd
