name: Imai test

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@master
        run: ls
        run: pwd

  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
     - run: python3 test.py
       run: ls
       run: pwd
